### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by dry11orange** [sony/easyhttpcpp#7]
### Expected behavior
Could you support  windows build

**Comment by shekharhimanshu** [comment]
Hi @dry11orange 

Thank you for your interest in EasyHttp.

Could you please share with us the cmake error and your cmake build steps?
Also could you tell us what version of Windows, Visual Studio you are using?

We are working on supporting Windows build in the coming months. (ETA is not yet decided)

**Comment by dry11orange** [comment]
when build easehttp, cmake show error message : need file "PocoConfig.cmake"
This file is from Poco

When I build poco with vs2015 sln, this file(PocoConfig.cmake) will not be generated
with cmake, this file will be generated.
But with cmake , I can't build poco correctly....

this is better example for using poco with cmake
https://github.com/RangelReale/pcacheproxy

**Comment by shekharhimanshu** [comment]
Yes, you will have to build (& install) Poco in order to use EasyHttp.
You can pass information about the installed Poco libraries by setting the `CMAKE_PREFIX_PATH` with your cmake command.

Your cmake option should look like below (change the Poco install dir to actual value)
```
-DCMAKE_PREFIX_PATH=path/to/Poco/install/dir
```
See Wiki, https://github.com/sony/easyhttpcpp/wiki/Installing-EasyHttp#build-easyhttp

>When I build poco with vs2015 sln, this file(PocoConfig.cmake) will not be generated

Where are you looking for config files? How are you building Poco? config files will generally be installed inside the CMAKE_INSTALLED_PATH.

**Comment by dry11orange** [comment]
ok
Thank you
